List<String> transactionNames = [
  'New shoes',
  'Weekly grocery',
  'Transportation',
  'Wedding',
  'Condom',
  'Birthday gift',
  'Eating at McDonald',
  'Electric bill',
  'Apartment rent',
  'Haircut',
  'Eating out',
  'Home improvement',
  'Pet food',
  'New guitar',
  'Rental car',
  'Gas & fuel',
  'Alcohol & bar',
  'Discounted chocolate',
  'Steam summer sale',
  'Business meal',
  'Clothing',
  'One-time hooker',
  'Monthly laundry',
  'Mr Beast donation',
  'Fixing toilet',
  'Coffee with Paul',
  'Weekend party',
  'Lastpass subscription',
  'Cyberpunk 2077 pre-ordering',
  'Paying debt',
  'Macau Gambling',
];